//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShenmueTextureOverride.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShenmueTextureOverride.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;Mappings&quot; : [
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_b.chrm_/ykb_b_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_b.chrm_/ykb_b_0.dds&quot;,
        ///   &quot;TextureID&quot; : &quot;9B4B425F4D55465F&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_b.chrm_/ykb_b_1.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_b.chrm_/ykb_b_1.dds&quot;,
        ///   &quot;TextureID&quot; : &quot;9B4B425F4D55425F&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_f.chrm_/ykb_f_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_f.chrm_/y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDTextureOverride_SM1 {
            get {
                return ResourceManager.GetString("SDTextureOverride_SM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;Mappings&quot; : [
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_b.chrm_/ykb_b_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_b.chrm_/ykb_b_0.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_b.chrm_/ykb_b_1.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_b.chrm_/ykb_b_1.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_f.chrm_/ykb_f_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/coldinit/ykb_f.chrm_/ykb_f_0.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/coldinit/ykb_f.chrm_/ykb_f_1.dd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDTextureOverride_SM1_Clean {
            get {
                return ResourceManager.GetString("SDTextureOverride_SM1_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;Mappings&quot; : [
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr02mpg.mt7_/abr02mpg_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr02mpg.mt7_/abr02mpg_0.dds&quot;,
        ///   &quot;TextureID&quot; : &quot;9FA2D19A8A58585F&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr02mpg.mt7_/abr02mpg_1.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr02mpg.mt7_/abr02mpg_1.dds&quot;,
        ///   &quot;TextureID&quot; : &quot;9FD8D19A8958585F&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr0hmpg.mt7_/abr0hmpg_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr0hmpg.mt7_/abr0hmpg_0.dds&quot;,
        ///   &quot;Textur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDTextureOverride_SM2 {
            get {
                return ResourceManager.GetString("SDTextureOverride_SM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;Mappings&quot; : [
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr02mpg.mt7_/abr02mpg_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr02mpg.mt7_/abr02mpg_0.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr02mpg.mt7_/abr02mpg_1.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr02mpg.mt7_/abr02mpg_1.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr0hmpg.mt7_/abr0hmpg_0.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/textureoverride/misc/abr0hmpg.mt7_/abr0hmpg_0.dds&quot;
        ///  },
        ///  {
        ///   &quot;Source&quot; : &quot;/misc/abr0hmpg.mt7_/abr0hmpg_1.dds&quot;,
        ///   &quot;Destination&quot; : &quot;/te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDTextureOverride_SM2_Clean {
            get {
                return ResourceManager.GetString("SDTextureOverride_SM2_Clean", resourceCulture);
            }
        }
    }
}
